### PR TITLE
Write object on target thread for MPWStreamingStream

### PR DESCRIPTION
**Pull request by Amin-Rehman**
Write object on target thread for MPWStreamingStream.

### CODE REVIEW

**Comment by mkarp** [comment]
@Amin-Rehman Please pay attention also to the error target. Should we write on the target thread to it too?

**Comment by mpw** [comment]
Hi Guys,

please don't do this as a special-case in the the URL fetcher, as there already are several mechanisms that can and do perform this job.

First, the NSURLSession has a delegate queue that is used to deliver results.  It is set to nil in the streamer, but doesn't have to be.  Second, there is the ThreadSwitchStream, which you can just place between whatever filter you had intended as the target and this.

See "Make each program do one thing well. To do a new job, build afresh rather than complicate old programs by adding new "features"."

https://en.wikipedia.org/wiki/Unix_philosophy

**Comment by amrehman** [comment]
@mkarp 
We don't have the concept of an ```errorTarget``` in the streamer.
In the code base, we restart the streamer (on the main thread!) in case the streamer is closed. 

I suppose the assumption is, if the streamer closed, after being started, surely there must have been an error so lets restart it after some delay.
Not arguing we shouldn't change this behavior, but thats how things are laid out at the moment :)

Addition:
In case we do get an error from the delegate:
```
- (void)URLSession:(NSURLSession *)session task:(NSURLSessionTask *)task
didCompleteWithError:(nullable NSError *)error
{
    @synchronized (self) {
        [self.inflight removeObject:task];
    }
    if ( error ){
        [self reportError:error];
    }
    [target close];
}
```
We report the error (which is simply a NSLog) and we close the streamer, perhaps we could call [target close] in the target thread, but inside the XOChangeNotificationStream..

```
- (void)close
{
    self.isRunning = NO;
    [self performSelectorOnMainThread:@selector(restartNotificationStreamer)
                           withObject:nil
                        waitUntilDone:NO];
}
```

So its kinda pointless. :S

**Comment by mkarp** [comment]
@mpw Marcel, when I read the PR (and having solved a similar problem myself), I've thought about doing exactly the same things that you've mentioned. I agree with you that applying Unix philosophy is a great idea. I think that Amin's solution aligns better to it, because it adheres to the rules of transparency and least surprise. I'll try to explain why.

What bothers me with the URLFetchers, is that from looking at their interfaces it's unclear which thread they will write results on. Both me and @Amin-Rehman think that specifying a target thread as a parameter is a much clear (to the reader) solution, rather than having to remember that it can write on one of the threads that its `NSOperationQueue` spawns. Why? Because just by looking at the interface, reader may find out that there's a possibility of specifying a target thread, and thus it may raise their awareness that the URLFetcher may write results on an arbitrary thread. If we rely on reader's understanding that they need to use a ThreadSwitchStream, then there are several options of how will they find out about it: documentation, trying it out, and reading the implementation (the list is not meant to be exhaustive). Would you agree that self-documenting interfaces are better?

As you've mentioned, adding additional parameters and code dillutes the idea of "doing one thing well." I would argue that URLFetchers don't do their one thing well enough. It's exactly the fact that we didn't expect the inner `NSURLSession` writing on an arbitrary thread of its `NSOperationQueue` that made us debug threading issues for multiple hours. The problem was multi-layered, lead to stuck sync issues in our clients and caused lots of negative user feedback. Yes, we were holding it wrong, but how could we have known? There were no obvious symptoms. Due to this, I don't think that we can call the URLFetcher a very robust tool, and I don't think that if the tool is not very robust then it does its one thing well enough.

I think Amin's addition brings a very healthy ratio of readability compared to the amount of code added.

Marcel, I'm still very open to any commentary from your side, and I would appreciate it.

**Comment by amrehman** [comment]
@mpw Always open to suggestions, yes. 
Thank you for the summary @mkarp

**Comment by mpw** [comment]
The behavior you don't like and that you found surprising is that of the underlying NSURLSession, not MPWURLFetchStream.  It also took me a day or more to get through all the details (or at least enough of the details to get to something actionable), alas that's just how the platform operates.

MPWURLFetchStream and friends' job is to adapt that to the pipe/filter style, and nothing more. Streams by themselves do not care what thread they are executed on, so placing the result on a particular thread is not the job of the MPWURLFetchStream.

What you are describing are (a) problems in a specific context and (b) already solved by a filter.

So once again, the solution is to combine the filters in such a fashion as to solve the problem at hand, not to modify the filters.

That said, there are two problems:  first is that the streaming stream does not expose the operation queue, so you cannot control it externally.  The second is that MPWURLFetchStream actually does do a second thing, specifically the hard throttling.  

Both of theses issues have been addressed in the current HEAD of the GitHub master.  There is an additional initializer that gets passed an NSOperationQueue and the throttling behavior has been extracted to a separate filter.  Now that the behavior is extracted, it has also become testable and thus also has tests.  What's more, it's now more obvious that other solutions than sleeping might be preferable, for example just buffering the requests and returning immediately.

Trying out such alternate behaviors is now as simple as plugging in a new filter, without the need to convince a recalcitrant upstream maintainer ;-) 


https://github.com/mpw/MPWFoundation/commit/c20d87b6b69d5d10b288f957f4f5b45c901fee9b

**Pull request merged**
